name: CMake CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Configure CMake
      run: cmake -B build -S . -DCMAKE_BUILD_TYPE=Release -G Ninja

    - name: Build Project
      run: cmake --build build --config Release

    - name: Run Tests
      run: ctest --test-dir build -C Release --output-on-failure

  cpp-linter:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: read
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Configure CMake (Export Compile Commands)
      run: cmake -B build -S . -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -G Ninja

    - name: Run C++ Linter
      uses: cpp-linter/cpp-linter-action@8e85cd02c8c3fe3ae527c94b5683fe2366b144ed # v2.20.0
      id: linter
      env:
        GITHUB_TOKEN: ${{ github.event_name == 'pull_request' && secrets.GITHUB_TOKEN || '' }}
      with:
        style: 'file'
        tidy-checks: ''
        database: 'build'
        version: '20'
        files-changed-only: true
        thread-comments: ${{ github.event_name == 'pull_request' && 'true' || 'false' }}
        extra-args: '-I${{ github.workspace }}/include'
